name: Build Flutter APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag untuk release. Contoh: v1.0.0'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-${{ inputs.release_tag || github.ref_name }}
          path: build/app/outputs/flutter-apk/*.apk

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag || github.ref_name }}
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
